blank_issues_enabled: false
contact_links:
  - name: 💬 Questions & ideas
    url: https://github.com/orgs/digital-multiverse/discussions
    about: Ask questions and discuss ideas here.
  - name: 🌱 Echoes of the Garden
    url: https://echoesofthegarden.com
    about: Newsletter and game info.
